### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by Robinlovelace** [JosiahParry/anime#8]
I may be up for giving this a go.

**Comment by Robinlovelace** [comment]
First attempt (still needs Rust installation): https://github.com/JosiahParry/anime/pull/7/commits/65d4dbf8d88745fde57db1a0e3ed2692b0438ba0

**Comment by Robinlovelace** [comment]
This one sorry: https://github.com/JosiahParry/anime/pull/7/commits/3dc1c60185fb5f0835872c25b40b3efc5ba92aab

**Comment by Robinlovelace** [comment]
Just a note on this: it should be `          working-directory: r` here:

**Comment by Robinlovelace** [comment]
https://github.com/JosiahParry/anime/blob/b648f9d03d100396969a5c6bdc7080f596a31444/.github/workflows/R-CMD-check.yaml#L47-L53

**Comment by Robinlovelace** [comment]
Inspiration: https://github.com/apache/arrow-nanoarrow/blob/main/.github/workflows/r-check.yaml#L77C1-L77C31

Will get back on it after the holidays, happy festive season Josiah!

**Comment by JosiahParry** [comment]
This is working! Thank you. 

CI will fail on r-devel because of a change CRAN developers have made and the issue is being ignored.

https://bugs.r-project.org/show_bug.cgi?id=18806

**Comment by Robinlovelace** [comment]
Amazing! We can create a new issue for website etc.
